# Generated by Django 3.1.1 on 2020-09-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgimage',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Users/wanted/Documents/Coding/homebase/backend/src/background/images/bgImage.jpg'),
        ),
    ]
