# Generated by Django 3.1.1 on 2020-09-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20200928_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Users/wanted/Documents/Coding/homebase/backend/src/background/images'),
        ),
    ]
