# Generated by Django 3.1.1 on 2020-09-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20200928_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimage',
            name='name',
            field=models.CharField(default='Placeholder name', max_length=30),
        ),
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(default='/Users/wanted/Documents/Coding/homebase/backend/src/background/images/default.jpg', upload_to='Users/wanted/Documents/Coding/homebase/backend/src/background/images/bgImage.jpg'),
        ),
    ]
