# Generated by Django 3.1.1 on 2020-09-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todoList',
            new_name='toDo',
        ),
    ]
